version: '3'

services:
  client:
    image: node:lts-alpine
    container_name: client
    working_dir: /client
    command: npm run dev
    volumes:
      - ./node_modules:/client/node_modules
      - ./client:/client
    ports:
      - 3000:3000

  api:
    image: node:lts-alpine
    container_name: api
    working_dir: /api
    command: npm run start:dev
    volumes:
      - ./node_modules:/api/node_modules
      - ./api:/api
    ports:
      - 3001:3000