import Head from "next/head";
import Button from "@/components/Button";
import Link from "next/link";
import Layout from "@/components/Layout";
import { useAuth } from "@/hooks/useAuth";
import Title from "@/components/Title";

export default function Home() {
  const { user } = useAuth();

  return (
    <Layout>
      <Head>
        <title>Nextar User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title label={`Hello ${user?.username ?? 'Visitor'}!`} />
      <Link href="/users">
        <Button>Users</Button>
      </Link>
      <Link href="/users/create">
        <Button>Create User</Button>
      </Link>
    </Layout>
  );
}
