import Head from "next/head";
import NavBar from "@/components/NavBar";
import Button from "@/components/Button";
import SearchInput from "@/components/SearchInput";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextar User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <span>Oloco meu</span>
        <SearchInput onSearch={console.log} />
        <Button>Botãozinho</Button>
      </NavBar>
      <Link href="/users">
        <Button>Users</Button>
      </Link>
    </>
  );
}
